

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler_jd
    username: root
    password: root


indexUrl: https://www.jd.com/
server:
  port: 8000